# https://mdformat.readthedocs.io/en/stable/users/configuration_file.html

# Use consecutive numbering (1., 2., 3.) for ordered lists.
number = true

# Set maximum line width for word wrapping
wrap = 80
