name: Source Code

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [master]

# To cancel a currently running workflow from the same PR, branch, or tag
# when a new workflow is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sources:
    name: Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create VERSION.txt
        run: bin/create-version-file.sh

      - name: Verify tutorial savefile
        run: bin/verify-tutorial.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: Sil-Q-src
          path: .
          # Otherwise directories such as `lib/apex/` are excluded, which only
          # contain a stub `.keepalive` or `.gitignore` file.  Without these
          # pre-generated directories, the game will have problems at run-time.
          include-hidden-files: true
          if-no-files-found: error

